# Generated by Django 4.0 on 2022-01-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_author_book_is_bestseeling_alter_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestseeling',
            new_name='is_bestselling',
        ),
    ]
